// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using portscanner_backend.Data;

#nullable disable

namespace portscanner_backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("portscanner_backend.Models.Branch", b =>
                {
                    b.Property<int>("Branch_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Branch_id"), 1L, 1);

                    b.Property<string>("Branch_cidr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Branch_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Branch_id");

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("portscanner_backend.Models.IpAddress", b =>
                {
                    b.Property<int>("Ip_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Ip_id"), 1L, 1);

                    b.Property<string>("Ip_address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ip_branchId")
                        .HasColumnType("int");

                    b.HasKey("Ip_id");

                    b.HasIndex("Ip_branchId");

                    b.ToTable("IpAddresses");
                });

            modelBuilder.Entity("portscanner_backend.Models.Port", b =>
                {
                    b.Property<int>("Port_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Port_id"), 1L, 1);

                    b.Property<int>("Port_branchId")
                        .HasColumnType("int");

                    b.Property<int>("Port_number")
                        .HasColumnType("int");

                    b.HasKey("Port_id");

                    b.HasIndex("Port_branchId");

                    b.ToTable("Ports");
                });

            modelBuilder.Entity("portscanner_backend.Models.PortGroup", b =>
                {
                    b.Property<int>("Pg_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Pg_id"), 1L, 1);

                    b.Property<string>("Pg_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Pg_id");

                    b.ToTable("PortGroups");
                });

            modelBuilder.Entity("portscanner_backend.Models.PortMaster", b =>
                {
                    b.Property<int>("Pm_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Pm_id"), 1L, 1);

                    b.Property<string>("Pm_desc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Pm_portGroup")
                        .HasColumnType("int");

                    b.Property<int>("Pm_portNumber")
                        .HasColumnType("int");

                    b.HasKey("Pm_id");

                    b.HasIndex("Pm_portGroup");

                    b.ToTable("PortMasters");
                });

            modelBuilder.Entity("portscanner_backend.Models.ScanResult", b =>
                {
                    b.Property<int>("Res_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Res_id"), 1L, 1);

                    b.Property<int>("Res_ipAddressId")
                        .HasColumnType("int");

                    b.Property<int>("Res_portId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Res_scanDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Res_status")
                        .HasColumnType("bit");

                    b.HasKey("Res_id");

                    b.HasIndex("Res_ipAddressId");

                    b.HasIndex("Res_portId");

                    b.ToTable("ScanResults");
                });

            modelBuilder.Entity("portscanner_backend.Models.IpAddress", b =>
                {
                    b.HasOne("portscanner_backend.Models.Branch", "Branch")
                        .WithMany("IpAddresses")
                        .HasForeignKey("Ip_branchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("portscanner_backend.Models.Port", b =>
                {
                    b.HasOne("portscanner_backend.Models.Branch", "Branch")
                        .WithMany("Ports")
                        .HasForeignKey("Port_branchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("portscanner_backend.Models.PortMaster", b =>
                {
                    b.HasOne("portscanner_backend.Models.PortGroup", "PortGroup")
                        .WithMany("PortMasters")
                        .HasForeignKey("Pm_portGroup")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PortGroup");
                });

            modelBuilder.Entity("portscanner_backend.Models.ScanResult", b =>
                {
                    b.HasOne("portscanner_backend.Models.IpAddress", "IpAddress")
                        .WithMany("ScanResults")
                        .HasForeignKey("Res_ipAddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("portscanner_backend.Models.Port", "Port")
                        .WithMany("ScanResults")
                        .HasForeignKey("Res_portId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IpAddress");

                    b.Navigation("Port");
                });

            modelBuilder.Entity("portscanner_backend.Models.Branch", b =>
                {
                    b.Navigation("IpAddresses");

                    b.Navigation("Ports");
                });

            modelBuilder.Entity("portscanner_backend.Models.IpAddress", b =>
                {
                    b.Navigation("ScanResults");
                });

            modelBuilder.Entity("portscanner_backend.Models.Port", b =>
                {
                    b.Navigation("ScanResults");
                });

            modelBuilder.Entity("portscanner_backend.Models.PortGroup", b =>
                {
                    b.Navigation("PortMasters");
                });
#pragma warning restore 612, 618
        }
    }
}
